# Generated by Django 4.2.23 on 2025-08-20 20:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlEnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('fruta_y_verdura', models.BooleanField(default=False)),
                ('fecha_y_hora_entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_y_hora_recogida', models.DateTimeField(blank=True, null=True)),
                ('fecha_y_hora_preparacion', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Benef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_beneficiario', models.CharField(max_length=10)),
                ('nombre_representante', models.CharField(max_length=100)),
                ('primer_apellido_representante', models.CharField(max_length=100)),
                ('segundo_apellido_representante', models.CharField(max_length=100)),
                ('numero_personas', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('telefono_secundario', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('fecha_alta', models.DateField()),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('numero_ninios', models.IntegerField()),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Donante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_donante', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('provincia', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('responsable', models.CharField(max_length=100)),
                ('fecha_alta', models.DateField()),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alimento', models.CharField(max_length=100)),
                ('fruta_y_verdura', models.BooleanField(default=False)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateTimeField()),
                ('peso', models.FloatField()),
                ('benef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refood_app.benef')),
            ],
        ),
        migrations.CreateModel(
            name='AlSal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateTimeField()),
                ('al_ent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refood_app.alent')),
                ('benef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refood_app.benef')),
            ],
        ),
        migrations.AddField(
            model_name='alent',
            name='donante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refood_app.donante'),
        ),
        migrations.AddField(
            model_name='alent',
            name='tipo_al',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refood_app.tipoal'),
        ),
    ]
