# Generated by Django 5.2.4 on 2025-07-22 18:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlEnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('fecha_y_hora_entrada', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Benef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_beneficiario', models.CharField(max_length=20, unique=True, verbose_name='Beneficiary ID')),
                ('nombre_representante', models.CharField(max_length=100)),
                ('numero_personas', models.IntegerField()),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_donante', models.CharField(max_length=20, unique=True, verbose_name='Donor ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alimento', models.CharField(max_length=100)),
                ('fruta_y_verdura', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('fecha_salida', models.DateTimeField(default=django.utils.timezone.now)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refood_app.benef')),
            ],
        ),
        migrations.CreateModel(
            name='AlSal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alimento_entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='porciones_salida', to='refood_app.alent')),
                ('checkout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='porciones', to='refood_app.checkout')),
            ],
        ),
        migrations.AddField(
            model_name='alent',
            name='donante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refood_app.donante'),
        ),
        migrations.AddField(
            model_name='alent',
            name='tipo_al',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refood_app.tipoal'),
        ),
    ]
